//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Briscola.View.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Briscola.View.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Error_InvalidChoice {
            get {
                return ResourceManager.GetString("Error_InvalidChoice", resourceCulture);
            }
        }
        
        public static string Error_Unexpected {
            get {
                return ResourceManager.GetString("Error_Unexpected", resourceCulture);
            }
        }
        
        public static string Header_MatchInfo {
            get {
                return ResourceManager.GetString("Header_MatchInfo", resourceCulture);
            }
        }
        
        public static string Label_Choice {
            get {
                return ResourceManager.GetString("Label_Choice", resourceCulture);
            }
        }
        
        public static string Label_ChooseCard {
            get {
                return ResourceManager.GetString("Label_ChooseCard", resourceCulture);
            }
        }
        
        public static string Label_Deck {
            get {
                return ResourceManager.GetString("Label_Deck", resourceCulture);
            }
        }
        
        public static string Label_Table {
            get {
                return ResourceManager.GetString("Label_Table", resourceCulture);
            }
        }
        
        public static string Match_Ended {
            get {
                return ResourceManager.GetString("Match_Ended", resourceCulture);
            }
        }
        
        public static string Match_Lose {
            get {
                return ResourceManager.GetString("Match_Lose", resourceCulture);
            }
        }
        
        public static string Match_ScoreLine {
            get {
                return ResourceManager.GetString("Match_ScoreLine", resourceCulture);
            }
        }
        
        public static string Match_Tie {
            get {
                return ResourceManager.GetString("Match_Tie", resourceCulture);
            }
        }
        
        public static string Match_TrickSummary {
            get {
                return ResourceManager.GetString("Match_TrickSummary", resourceCulture);
            }
        }
        
        public static string Match_Win {
            get {
                return ResourceManager.GetString("Match_Win", resourceCulture);
            }
        }
        
        public static string Menu_ChooseOption {
            get {
                return ResourceManager.GetString("Menu_ChooseOption", resourceCulture);
            }
        }
        
        public static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        public static string Menu_Start1v1 {
            get {
                return ResourceManager.GetString("Menu_Start1v1", resourceCulture);
            }
        }
        
        public static string Menu_Start2v2 {
            get {
                return ResourceManager.GetString("Menu_Start2v2", resourceCulture);
            }
        }
        
        public static string Menu_StartHumanvCpuPreset {
            get {
                return ResourceManager.GetString("Menu_StartHumanvCpuPreset", resourceCulture);
            }
        }
        
        public static string Msg_Goodbye {
            get {
                return ResourceManager.GetString("Msg_Goodbye", resourceCulture);
            }
        }
        
        public static string Msg_InvalidChoice {
            get {
                return ResourceManager.GetString("Msg_InvalidChoice", resourceCulture);
            }
        }
        
        public static string Msg_NotImplemented {
            get {
                return ResourceManager.GetString("Msg_NotImplemented", resourceCulture);
            }
        }
        
        public static string Msg_PressEnterToReturn {
            get {
                return ResourceManager.GetString("Msg_PressEnterToReturn", resourceCulture);
            }
        }
        
        public static string Msg_Terminated {
            get {
                return ResourceManager.GetString("Msg_Terminated", resourceCulture);
            }
        }
        
        public static string Notify_PlayerPlayed {
            get {
                return ResourceManager.GetString("Notify_PlayerPlayed", resourceCulture);
            }
        }
        
        public static string Notify_TrickWonBy {
            get {
                return ResourceManager.GetString("Notify_TrickWonBy", resourceCulture);
            }
        }
        
        public static string Notify_YouDrawn {
            get {
                return ResourceManager.GetString("Notify_YouDrawn", resourceCulture);
            }
        }
        
        public static string Notify_YouPlayed {
            get {
                return ResourceManager.GetString("Notify_YouPlayed", resourceCulture);
            }
        }
        
        public static string Setup_1v1Header {
            get {
                return ResourceManager.GetString("Setup_1v1Header", resourceCulture);
            }
        }
        
        public static string Setup_Choice {
            get {
                return ResourceManager.GetString("Setup_Choice", resourceCulture);
            }
        }
        
        public static string Setup_ChooseStrategy {
            get {
                return ResourceManager.GetString("Setup_ChooseStrategy", resourceCulture);
            }
        }
        
        public static string Setup_ConfiguringPlayer {
            get {
                return ResourceManager.GetString("Setup_ConfiguringPlayer", resourceCulture);
            }
        }
        
        public static string Setup_DefaultPlayerName {
            get {
                return ResourceManager.GetString("Setup_DefaultPlayerName", resourceCulture);
            }
        }
        
        public static string Setup_EnterName {
            get {
                return ResourceManager.GetString("Setup_EnterName", resourceCulture);
            }
        }
        
        public static string Setup_InvalidStrategy {
            get {
                return ResourceManager.GetString("Setup_InvalidStrategy", resourceCulture);
            }
        }
        
        public static string Setup_StartingGame {
            get {
                return ResourceManager.GetString("Setup_StartingGame", resourceCulture);
            }
        }
        
        public static string Status_TrickWonBy {
            get {
                return ResourceManager.GetString("Status_TrickWonBy", resourceCulture);
            }
        }
        
        public static string Status_TurnOf {
            get {
                return ResourceManager.GetString("Status_TurnOf", resourceCulture);
            }
        }
        
        public static string Status_YourTurn {
            get {
                return ResourceManager.GetString("Status_YourTurn", resourceCulture);
            }
        }
        
        public static string Suit_Clubs {
            get {
                return ResourceManager.GetString("Suit_Clubs", resourceCulture);
            }
        }
        
        public static string Suit_Coins {
            get {
                return ResourceManager.GetString("Suit_Coins", resourceCulture);
            }
        }
        
        public static string Suit_Cups {
            get {
                return ResourceManager.GetString("Suit_Cups", resourceCulture);
            }
        }
        
        public static string Suit_Swords {
            get {
                return ResourceManager.GetString("Suit_Swords", resourceCulture);
            }
        }
        
        public static string Value_Ace {
            get {
                return ResourceManager.GetString("Value_Ace", resourceCulture);
            }
        }
        
        public static string Value_Five {
            get {
                return ResourceManager.GetString("Value_Five", resourceCulture);
            }
        }
        
        public static string Value_Four {
            get {
                return ResourceManager.GetString("Value_Four", resourceCulture);
            }
        }
        
        public static string Value_Jack {
            get {
                return ResourceManager.GetString("Value_Jack", resourceCulture);
            }
        }
        
        public static string Value_King {
            get {
                return ResourceManager.GetString("Value_King", resourceCulture);
            }
        }
        
        public static string Value_Knight {
            get {
                return ResourceManager.GetString("Value_Knight", resourceCulture);
            }
        }
        
        public static string Value_Seven {
            get {
                return ResourceManager.GetString("Value_Seven", resourceCulture);
            }
        }
        
        public static string Value_Six {
            get {
                return ResourceManager.GetString("Value_Six", resourceCulture);
            }
        }
        
        public static string Value_Three {
            get {
                return ResourceManager.GetString("Value_Three", resourceCulture);
            }
        }
        
        public static string Value_Two {
            get {
                return ResourceManager.GetString("Value_Two", resourceCulture);
            }
        }
        
        public static string CardFormat {
            get {
                return ResourceManager.GetString("CardFormat", resourceCulture);
            }
        }
    }
}
