//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Briscola.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Briscola.View.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string CardFormat {
            get {
                return ResourceManager.GetString("CardFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice. Must be a valid slot number and non-empty..
        /// </summary>
        internal static string Error_InvalidChoice {
            get {
                return ResourceManager.GetString("Error_InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: {0}.
        /// </summary>
        internal static string Error_Unexpected {
            get {
                return ResourceManager.GetString("Error_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briscola match (Turn number {0}).
        /// </summary>
        internal static string Header_MatchInfo {
            get {
                return ResourceManager.GetString("Header_MatchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice: .
        /// </summary>
        internal static string Label_Choice {
            get {
                return ResourceManager.GetString("Label_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your card:.
        /// </summary>
        internal static string Label_ChooseCard {
            get {
                return ResourceManager.GetString("Label_ChooseCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck ({0} cards), Briscola is .
        /// </summary>
        internal static string Label_Deck {
            get {
                return ResourceManager.GetString("Label_Deck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table:.
        /// </summary>
        internal static string Label_Table {
            get {
                return ResourceManager.GetString("Label_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Ended! .
        /// </summary>
        internal static string Match_Ended {
            get {
                return ResourceManager.GetString("Match_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve lost!.
        /// </summary>
        internal static string Match_Lose {
            get {
                return ResourceManager.GetString("Match_Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}: {1} points.
        /// </summary>
        internal static string Match_ScoreLine {
            get {
                return ResourceManager.GetString("Match_ScoreLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a tie!.
        /// </summary>
        internal static string Match_Tie {
            get {
                return ResourceManager.GetString("Match_Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; {0}. {1} won {2} pts.
        /// </summary>
        internal static string Match_TrickSummary {
            get {
                return ResourceManager.GetString("Match_TrickSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve won!.
        /// </summary>
        internal static string Match_Win {
            get {
                return ResourceManager.GetString("Match_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option: .
        /// </summary>
        internal static string Menu_ChooseOption {
            get {
                return ResourceManager.GetString("Menu_ChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Quit.
        /// </summary>
        internal static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Start 1v1 Match.
        /// </summary>
        internal static string Menu_Start1v1 {
            get {
                return ResourceManager.GetString("Menu_Start1v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Start 2v2 Match.
        /// </summary>
        internal static string Menu_Start2v2 {
            get {
                return ResourceManager.GetString("Menu_Start2v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye! :).
        /// </summary>
        internal static string Msg_Goodbye {
            get {
                return ResourceManager.GetString("Msg_Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice. Please press Enter and try again..
        /// </summary>
        internal static string Msg_InvalidChoice {
            get {
                return ResourceManager.GetString("Msg_InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is planned but not yet implemented..
        /// </summary>
        internal static string Msg_NotImplemented {
            get {
                return ResourceManager.GetString("Msg_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to return to the main menu....
        /// </summary>
        internal static string Msg_PressEnterToReturn {
            get {
                return ResourceManager.GetString("Msg_PressEnterToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Application terminated. Press any key to exit....
        /// </summary>
        internal static string Msg_Terminated {
            get {
                return ResourceManager.GetString("Msg_Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} played {1}.
        /// </summary>
        internal static string Notify_PlayerPlayed {
            get {
                return ResourceManager.GetString("Notify_PlayerPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trick won by {0} (earned {1} points).
        /// </summary>
        internal static string Notify_TrickWonBy {
            get {
                return ResourceManager.GetString("Notify_TrickWonBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve drawn {0} of {1}.
        /// </summary>
        internal static string Notify_YouDrawn {
            get {
                return ResourceManager.GetString("Notify_YouDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You played {0}.
        /// </summary>
        internal static string Notify_YouPlayed {
            get {
                return ResourceManager.GetString("Notify_YouPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- 1v1 Match Setup ---.
        /// </summary>
        internal static string Setup_1v1Header {
            get {
                return ResourceManager.GetString("Setup_1v1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Choice: .
        /// </summary>
        internal static string Setup_Choice {
            get {
                return ResourceManager.GetString("Setup_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Choose strategy:.
        /// </summary>
        internal static string Setup_ChooseStrategy {
            get {
                return ResourceManager.GetString("Setup_ChooseStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring Player {0}:.
        /// </summary>
        internal static string Setup_ConfiguringPlayer {
            get {
                return ResourceManager.GetString("Setup_ConfiguringPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0}.
        /// </summary>
        internal static string Setup_DefaultPlayerName {
            get {
                return ResourceManager.GetString("Setup_DefaultPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter name (leave blank for default): .
        /// </summary>
        internal static string Setup_EnterName {
            get {
                return ResourceManager.GetString("Setup_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Invalid choice. Please select a valid strategy number..
        /// </summary>
        internal static string Setup_InvalidStrategy {
            get {
                return ResourceManager.GetString("Setup_InvalidStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting game....
        /// </summary>
        internal static string Setup_StartingGame {
            get {
                return ResourceManager.GetString("Setup_StartingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trick won by {0}!.
        /// </summary>
        internal static string Status_TrickWonBy {
            get {
                return ResourceManager.GetString("Status_TrickWonBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s the turn of {0}....
        /// </summary>
        internal static string Status_TurnOf {
            get {
                return ResourceManager.GetString("Status_TurnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s your turn!.
        /// </summary>
        internal static string Status_YourTurn {
            get {
                return ResourceManager.GetString("Status_YourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        internal static string Suit_Clubs {
            get {
                return ResourceManager.GetString("Suit_Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coins.
        /// </summary>
        internal static string Suit_Coins {
            get {
                return ResourceManager.GetString("Suit_Coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cups.
        /// </summary>
        internal static string Suit_Cups {
            get {
                return ResourceManager.GetString("Suit_Cups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swords.
        /// </summary>
        internal static string Suit_Swords {
            get {
                return ResourceManager.GetString("Suit_Swords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace.
        /// </summary>
        internal static string Value_Ace {
            get {
                return ResourceManager.GetString("Value_Ace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        internal static string Value_Five {
            get {
                return ResourceManager.GetString("Value_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        internal static string Value_Four {
            get {
                return ResourceManager.GetString("Value_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack.
        /// </summary>
        internal static string Value_Jack {
            get {
                return ResourceManager.GetString("Value_Jack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        internal static string Value_King {
            get {
                return ResourceManager.GetString("Value_King", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        internal static string Value_Knight {
            get {
                return ResourceManager.GetString("Value_Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        internal static string Value_Seven {
            get {
                return ResourceManager.GetString("Value_Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        internal static string Value_Six {
            get {
                return ResourceManager.GetString("Value_Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        internal static string Value_Three {
            get {
                return ResourceManager.GetString("Value_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        internal static string Value_Two {
            get {
                return ResourceManager.GetString("Value_Two", resourceCulture);
            }
        }
    }
}
